# Generated by scripts/generate-stubs.py. Do not edit.
"""Built-in names generated from the Windows Rust shader catalog."""

from ._enums import _StringEnum


class BuiltinShader(_StringEnum):
    """Built-in shader sources; compilation requires Windows."""

    Identity = 'identity'
    Glitch = 'glitch'
    ParticleVortex = 'particle-vortex'
    DustTransfer = 'dust-transfer'
    SilkFlow = 'silk-flow'
