# Generated by scripts/generate-stubs.py. Do not edit.
from enum import Enum
'Built-in names generated from the Windows Rust shader catalog.'

class BuiltinShader(str, Enum):
    """Built-in shader sources; compilation requires Windows."""
    Identity = 'identity'
    Glitch = 'glitch'
    ParticleVortex = 'particle-vortex'
    DustTransfer = 'dust-transfer'
    SilkFlow = 'silk-flow'
