# Generated by scripts/generate-stubs.py. Do not edit.
"""String-compatible choices accepted by the native bindings."""
from enum import Enum

class KeyframeInterp(str, Enum):
    """Interpolation between sampled or explicit keyframes."""
    Linear = 'linear'
    Step = 'step'
    SmoothStep = 'smoothstep'

class ShaderPipeline(str, Enum):
    """Geometry pipeline used by a shader source."""
    Sprite = 'sprite'
    Particles = 'particles'
    Procedural = 'procedural'

class FolderFlagOpKind(str, Enum):
    """Folder-flag operation discriminator for dict and tuple inputs."""
    Set = 'set'
    Exactly = 'exactly'

class CurveKind(str, Enum):
    """Representation of an animation curve."""
    Builtin = 'builtin'
    Keyframe = 'keyframe'

class DurationKind(str, Enum):
    """How an animation duration is resolved."""
    Fixed = 'fixed'
    Distance = 'distance'

class FinishReasonKind(str, Enum):
    """Discriminator of an animation's finish reason."""
    Completed = 'completed'
    Stopped = 'stopped'
    Error = 'error'

class LogTarget(str, Enum):
    """Destination for native tracing events."""
    Loguru = 'loguru'
    Stderr = 'stderr'
