# Generated by scripts/generate-stubs.py. Do not edit.
from __future__ import annotations
from enum import IntFlag

class FolderFlag(IntFlag):
    """Combinable Windows flags accepted by all integer flag APIs.

    Construct ``FolderFlag(raw_mask)`` to retain unnamed bits. Titles and
    descriptions preserve the legacy UI where applicable, not support claims.
    Includes unsupported and deprecated flags; see Microsoft's reference:
    https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/ne-shobjidl_core-folderflags
    """
    FWF_NONE = 0
    FWF_AUTOARRANGE = 1
    FWF_ABBREVIATEDNAMES = 2
    FWF_SNAPTOGRID = 4
    FWF_OWNERDATA = 8
    FWF_BESTFITWINDOW = 16
    FWF_DESKTOP = 32
    FWF_SINGLESEL = 64
    FWF_NOSUBFOLDERS = 128
    FWF_TRANSPARENT = 256
    FWF_NOCLIENTEDGE = 512
    FWF_NOSCROLL = 1024
    FWF_ALIGNLEFT = 2048
    FWF_NOICONS = 4096
    FWF_SHOWSELALWAYS = 8192
    FWF_NOVISIBLE = 16384
    FWF_SINGLECLICKACTIVATE = 32768
    FWF_NOWEBVIEW = 65536
    FWF_HIDEFILENAMES = 131072
    FWF_CHECKSELECT = 262144
    FWF_NOENUMREFRESH = 524288
    FWF_NOGROUPING = 1048576
    FWF_FULLROWSELECT = 2097152
    FWF_NOFILTERS = 4194304
    FWF_NOCOLUMNHEADER = 8388608
    FWF_NOHEADERINALLVIEWS = 16777216
    FWF_EXTENDEDTILES = 33554432
    FWF_TRICHECKSELECT = 67108864
    FWF_AUTOCHECKSELECT = 134217728
    FWF_NOBROWSERVIEWSTATE = 268435456
    FWF_SUBSETGROUPS = 536870912
    FWF_USESEARCHFOLDER = 1073741824
    FWF_ALLOWRTLREADING = 2147483648

    @property
    def title(self) -> str | None:
        """Display title, or None for a combined or unnamed mask."""
        ...

    @property
    def description(self) -> str | None:
        """Display description, or None for a combined or unnamed mask."""
        ...
