# Generated by scripts/generate-stubs.py. Do not edit.
from __future__ import annotations
import sys
import typing
from ._builtin_shaders import BuiltinShader
from ._enums import KeyframeInterp, LogTarget

"""
Rust-powered Windows desktop icon controller and animator.
"""

from collections.abc import Sequence
from rusty_desktop_icons._enums import CurveKind, DurationKind, FinishReasonKind, FolderFlagOpKind, ShaderPipeline
from typing import Final, final
__author__: Final = "s0d3s"
__version__: Final[str]

@final
class AnimationHandle:
    """
    Handle returned by [`DesktopController.animate`].

    Cloneable and thread-safe: hand it to another Python thread that
    waits on completion while your main thread polls progress.
    """
    def __repr__(self, /) -> str: ...
    def final_commit(self, /) -> FinalCommitOutcome |None:
        """
        Outcome of the Shell-side final commit, once the animation has
        finished. `None` while it is still running, or if finalization
        itself failed (in which case `finish_reason()` carries the error).
        """
    def finish_reason(self, /) -> FinishReason |None:
        """
        Read the finish reason if the animation has already ended.
        """
    def is_running(self, /) -> bool:
        """
        `True` while the animation is still ticking.
        """
    def missing_icons(self, /) -> list[str]:
        """
        Ids listed in the spec but not present on the desktop at start.
        """
    def on_finish(self, /, cb: "typing.Callable[[FinishReason], None]") -> None: ...
    def on_icon_complete(self, /, cb: "typing.Callable[[str], None]") -> None: ...
    def on_start(self, /, cb: "typing.Callable[[StartContext], None]") -> None: ...
    def on_tick(self, /, cb: "typing.Callable[[TickContext], None]") -> None: ...
    def progress(self, /) -> float:
        """
        Global progress `∈ [0, 1]` (mean per-icon `t`).
        """
    def snapshot(self, /) -> list[IconAnimationState]:
        """
        Copy of the current per-icon state.
        """
    def stop(self, /, mode: StopMode |None = None) -> None:
        """
        Ask the engine to stop the animation.

        `mode` defaults to [`StopMode.LeaveInPlace`]. This is the only way
        to alter a running animation — to change targets or the icon set,
        stop, read `snapshot()`, and call `animate()` again.
        """
    def wait(self, /) -> FinishReason:
        """
        Block until the animation finishes. Releases the GIL while waiting.
        """
    def wait_timeout(self, /, timeout_seconds: float) -> FinishReason |None:
        """
        Block for up to `timeout_seconds`. Returns `None` on timeout.
        """

@final
class AnimationOptions:
    """
    Global animation options.

    All fields are optional; pass `None` (or omit) to keep the engine
    default. Also accepted as a plain dict at [`DesktopController.animate`].
    """
    def __new__(cls, /, tick_hz: int |None = None, position_tolerance_px: int |None = None, before_flags: "FolderFlagOp | tuple[str, int] | dict[str, object] | None" = None, after_flags: "FolderFlagOp | tuple[str, int] | dict[str, object] | None" = None, force_fallback: bool = False, draw_labels: bool = True, draw_shortcut_overlay: bool = True, draw_shield_overlay: bool = True, *, snap_to_grid: bool = False) -> AnimationOptions: ...
    def __repr__(self, /) -> str: ...
    @property
    def draw_labels(self, /) -> bool: ...
    @property
    def draw_shield_overlay(self, /) -> bool: ...
    @property
    def draw_shortcut_overlay(self, /) -> bool: ...
    @property
    def force_fallback(self, /) -> bool: ...
    @property
    def position_tolerance_px(self, /) -> int |None: ...
    @property
    def snap_to_grid(self, /) -> bool: ...
    @property
    def tick_hz(self, /) -> int |None: ...

@final
class AnimationPreset:
    """
    Platform-independent movement, strength envelope and duration values.

    Defaults are ease-in-out movement, smooth 15 percent strength fades and
    two seconds. Pass fields separately to IconAnimationSpec and Effect;
    presets never change constructor defaults or compile shaders.
    """
    def __new__(cls, /, *, movement: Curve |None = None, envelope: Curve |None = None, duration: Duration |None = None) -> AnimationPreset: ...
    @classmethod
    def builtin(cls, /, name: "BuiltinShader | str") -> AnimationPreset:
        """
        Look up recommendations from the Windows shader catalog without compilation.
        Raises UnsupportedPlatform on other systems; AnimationPreset() is portable.
        """
    @property
    def duration(self, /) -> Duration: ...
    @property
    def envelope(self, /) -> Curve: ...
    @property
    def movement(self, /) -> Curve: ...

@final
class Canvas:
    """
    Off-screen dimensions in physical pixels; icon_size is the baseline DIP slot size.
    """
    def __new__(cls, /, width: int, height: int, *, dpi_scale: float = 1.0, icon_size: int = 48) -> Canvas: ...
    @property
    def dpi_scale(self, /) -> float: ...
    @property
    def height(self, /) -> int: ...
    @property
    def icon_size(self, /) -> int: ...
    @property
    def width(self, /) -> int: ...

@final
class CapturedFrame:
    """
    Owned, tightly packed premultiplied BGRA pixels. Convert alpha before saving PNG.
    """
    @property
    def height(self, /) -> int: ...
    @property
    def pixel_format(self, /) -> str: ...
    @property
    def pixels(self, /) -> bytes: ...
    @property
    def seconds(self, /) -> float: ...
    @property
    def stride(self, /) -> int: ...
    @property
    def width(self, /) -> int: ...

@final
class Curve:
    """
    Animation curve.

    Every axis of every icon animation is driven by a value in `[0, 1]`
    produced by evaluating a `Curve`. Overshoot (values outside `[0, 1]`)
    is permitted.
    """
    def __repr__(self, /) -> str: ...
    @classmethod
    def bounce(cls, /, bounces: int = 3, decay: float = 0.5) -> Curve:
        """
        Bouncing curve — several damped rebounds converging on `1`.
        """
    @classmethod
    def cubic_bezier(cls, /, c1x: float, c1y: float, c2x: float, c2y: float) -> Curve:
        """
        CSS-style parametric cubic Bézier through `(0, 0)`, `(c1x, c1y)`,
        `(c2x, c2y)` and `(1, 1)`. `c1x` and `c2x` must lie in `[0, 1]`.
        """
    @classmethod
    def cubic_in(cls, /) -> Curve: ...
    @classmethod
    def cubic_in_out(cls, /) -> Curve: ...
    @classmethod
    def cubic_out(cls, /) -> Curve: ...
    @classmethod
    def ease_in(cls, /) -> Curve: ...
    @classmethod
    def ease_in_out(cls, /) -> Curve: ...
    @classmethod
    def ease_out(cls, /) -> Curve: ...
    @classmethod
    def elastic(cls, /, period: float = 0.3, amplitude: float = 1.0) -> Curve:
        """
        Elastic ease-out — sinusoidal overshoot damped by `2^(-10t)`.
        """
    def eval(self, /, t: float) -> float:
        """
        Evaluate the curve at `t` (saturated to `[0, 1]`).
        """
    @classmethod
    def from_function(cls, /, f: "typing.Callable[[float], float]", samples: int = 64, interp: "KeyframeInterp | str" = "linear") -> Curve:
        """
        Sample a Python callable `f(t) -> v` at `samples` evenly-spaced
        points in `[0, 1]` and build a keyframe curve.

        The callable is invoked **only** during this call and dropped
        immediately after; the resulting curve is pure data. Any exception
        raised by the callable becomes an `InvalidCurve` error.
        """
    @classmethod
    def from_motion_function(cls, /, f: "typing.Callable[[MotionContext, float], float]", origin: "typing.Sequence[int]", target: "typing.Sequence[int]", duration_seconds: float, params: dict[str, float] |None = None, samples: int = 64, interp: "KeyframeInterp | str" = "linear") -> Curve:
        """
        Sample a **motion-aware** Python callable `f(ctx, t) -> v` at
        `samples` evenly-spaced points in `[0, 1]`.

        The callable receives a
        [`MotionContext`](rusty_desktop_icons.MotionContext) built from
        `origin`, `target`, `duration_seconds` and `params`, plus the
        normalized time `t`. It is invoked only during this call.
        """
    @classmethod
    def keyframes(cls, /, keys: "list[tuple[float, float] | list[float] | dict[str, float]]", interp: "KeyframeInterp | str" = "linear") -> Curve:
        """
        Build a curve from an explicit list of `(t, v)` keyframes.

        `keys` must start with `(0.0, ...)`, end with `(1.0, ...)`, and be
        strictly ascending in `t`. Prefer `KeyframeInterp` members for `interp`;
        legacy strings and case-insensitive aliases remain accepted.
        """
    @property
    def kind(self, /) -> CurveKind:
        """
        Curve representation, compatible with the legacy string discriminator.
        """
    @classmethod
    def linear(cls, /) -> Curve: ...
    @classmethod
    def overshoot(cls, /, strength: float = 1.7) -> Curve:
        """
        Back / overshoot ease-in-out.
        """
    @classmethod
    def quad_in(cls, /) -> Curve: ...
    @classmethod
    def quad_in_out(cls, /) -> Curve: ...
    @classmethod
    def quad_out(cls, /) -> Curve: ...
    @classmethod
    def sine_in(cls, /) -> Curve: ...
    @classmethod
    def sine_in_out(cls, /) -> Curve: ...
    @classmethod
    def sine_out(cls, /) -> Curve: ...
    @classmethod
    def spring(cls, /, damping: float = 0.5, stiffness: float = 180.0, mass: float = 1.0) -> Curve:
        """
        Damped-cosine "spring" curve.
        """

@final
class DesktopController:
    """
    Top-level entry point for animating the current user's desktop.

    On Windows this drives the real `IFolderView2` COM interface. On other
    platforms every method raises `UnsupportedPlatform`.
    """
    def __new__(cls, /) -> DesktopController:
        """
        Spawn the worker thread and connect to the desktop backend.
        """
    def __repr__(self, /) -> str: ...
    def animate(self, /, specs: "typing.Iterable[IconAnimationSpec | dict[str, object]]", options: "AnimationOptions | dict[str, object] | None" = None) -> AnimationHandle:
        """
        Start a fixed set of icon animations and return immediately with a handle.
        """
    def apply_flags(self, /, mask: int, values: int) -> None:
        """
        Perform a masked update of the desktop folder-view flags.

        `new_flags = (old_flags & !mask) | (values & mask)`

        Raises `AnimationBusy` while an animation is running.
        """
    def desktop_info(self, /) -> DesktopInfo: ...
    def get_flags(self, /) -> int:
        """
        Read the raw desktop folder-view flag word.
        """
    def list_icons(self, /) -> list[IconSnapshot]:
        """
        Snapshot every icon currently on the desktop.
        """
    def list_monitors(self, /) -> list[MonitorInfo]:
        """
        Enumerate every connected display.

        Returns a list of [`MonitorInfo`] objects whose `bounds` share
        the same virtual-screen coordinate space as icon positions.
        Callers can pick a monitor and build target positions within
        its `work_area` to place icons intelligently on multi-monitor
        setups.
        """
    def monitor_for_point(self, /, point: "typing.Sequence[int]") -> MonitorInfo |None:
        """
        Look up which monitor contains a given `(x, y)` point.

        Returns `None` if the point falls outside every monitor's
        bounds — which can happen for points in the "dead" space
        between mismatched-resolution monitors.
        """
    def prepare(self, /, specs: "typing.Iterable[IconAnimationSpec | dict[str, object]]", options: "AnimationOptions | dict[str, object] | None" = None) -> PreparedAnimation:
        """
        Prepare artwork and GPU resources without starting the visual clock.
        """
    def prepare_scene(self, /, canvas: Canvas, specs: "typing.Iterable[IconAnimationSpec | dict[str, object]]", positions: "typing.Iterable[tuple[str, typing.Sequence[int]] | dict[str, object]]", options: "AnimationOptions | dict[str, object] | None" = None) -> RenderSession:
        """
        Prepare artwork and GPU resources without starting the visual clock.

        Scene positions are independent of real desktop coordinates. Every spec must
        have exactly one origin; absent desktop icons/artwork fail preparation.
        """
    def render_overlay_snapshot(self, /, width: int, height: int, dpi_scale: float, positions: "typing.Iterable[tuple[str, typing.Sequence[int]] | dict[str, object]]", options: "AnimationOptions | dict[str, object] | None" = None) -> "dict[str, object]":
        """
        Render one frame of the overlay off-screen with pixel and geometry data.

        `positions` is an iterable of `(icon_id, (x, y))` pairs (or
        dicts with `id` / `position` keys), where `(x, y)` are in
        **overlay-local pixel coordinates** — i.e. the top-left of the
        snapshot buffer is `(0, 0)`. `dpi_scale` picks the render DPI
        (`1.0` → 96 DPI, `2.5` → 240 DPI). `options` accepts the same
        three feature toggles as `AnimationOptions` (`draw_labels`,
        `draw_shortcut_overlay`, `draw_shield_overlay`).

        Returns a dictionary with ``pixels`` (premultiplied BGRA bytes),
        ``width``, ``height`` and ``geometry``. Each geometry entry contains
        ``id``, ``icon_rect_px``, ``label_rect_px`` and ``arrow_rect_px``.
        The pixel buffer has length ``width * height * 4``. Wrap it with Pillow
        using ``Image.frombuffer("RGBA", (width, height), result["pixels"], "raw", "BGRA", 0, 1)``.

        Never touches the display mode or an on-screen window. Call
        `list_icons()` first so the backend's PIDL/name caches are
        populated; unknown ids render as placeholder tiles.
        """
    def set_flags(self, /, flags: int) -> None:
        """
        OR-set semantics.
        """
    def set_flags_exactly(self, /, flags: int) -> None:
        """
        Exactly-set semantics — expands `flags` via `build_true_mask`.
        """
    def set_positions(self, /, moves: "typing.Iterable[tuple[str, typing.Sequence[int]] | dict[str, object]]") -> list[str]:
        """
        Instantly move a batch of icons.

        `moves` is an iterable of `(icon_id, (x, y))` pairs (or dicts with
        `id` / `position` keys). Returns the list of icon ids the backend
        could not resolve. Raises `AnimationBusy` while an animation is
        running.
        """
    def toggle_flags(self, /, flags: int) -> None:
        """
        XOR-toggle semantics.
        """
    def unset_flags(self, /, flags: int) -> None:
        """
        AND-clear semantics.
        """

@final
class DesktopInfo:
    def __repr__(self, /) -> str: ...
    @property
    def bounds(self, /) -> Rect: ...
    @property
    def grids(self, /) -> list[IconGrid]: ...
    @property
    def monitors(self, /) -> list[MonitorInfo]: ...
    def to_dict(self, /) -> "dict[str, object]": ...

@final
class Duration:
    """
    Duration policy for an animation.

    Build with one of the classmethod constructors::

        Duration.fixed(seconds=1.0)
        Duration.distance(speed_px_per_sec=250.0)
        Duration.distance_clamped(
            speed_px_per_sec=250.0,
            min_seconds=0.15,
            max_seconds=1.5,
        )
    """
    def __repr__(self, /) -> str: ...
    @classmethod
    def distance(cls, /, speed_px_per_sec: float) -> Duration:
        """
        Duration derived from movement distance and a constant speed.
        """
    @classmethod
    def distance_clamped(cls, /, speed_px_per_sec: float, min_seconds: float, max_seconds: float) -> Duration:
        """
        Duration derived from distance and speed, clamped to
        `[min_seconds, max_seconds]`.
        """
    @classmethod
    def fixed(cls, /, seconds: float) -> Duration:
        """
        A fixed wall-clock duration.
        """
    @property
    def kind(self, /) -> DurationKind:
        """
        Duration representation, compatible with the legacy string discriminator.
        """

@final
class Effect:
    def __new__(cls, /, shader: Shader, *, params: tuple[float, float, float, float] |None = None, parameters: dict[str, float] |None = None, envelope: Curve |None = None, padding_px: int = 16, seed: float = 0.0) -> Effect: ...
    @property
    def padding_px(self, /) -> int: ...
    @property
    def parameters(self, /) -> dict[str, float]: ...
    @property
    def params(self, /) -> tuple[float, float, float, float]: ...

@final
class EffectParameter:
    def __new__(cls, /, name: str, default: float, *, min: float, max: float, kind: str = "float") -> EffectParameter: ...
    @property
    def default(self, /) -> float: ...
    @property
    def kind(self, /) -> str: ...
    @property
    def max(self, /) -> float: ...
    @property
    def min(self, /) -> float: ...
    @property
    def name(self, /) -> str: ...

@final
class FinalCommitOutcome:
    """
    Result of the Shell-side final commit at the end of an animation.

    Returned by [`AnimationHandle.final_commit`]; `None` there means the
    outcome is unknown (still running, or finalization itself failed).

    `moved_ids` is a **confirmation signal, not a census** — the Windows
    backend stops polling the Shell at the first icon that lands, so a
    successful 200-icon commit reports a single id. Non-empty means "the
    commit reached the Shell".

    `missing_ids` **is** complete: every id listed there could not be
    resolved and was left wherever the Shell last had it.
    """
    def __repr__(self, /) -> str: ...
    @property
    def missing_ids(self, /) -> list[str]: ...
    @property
    def moved_ids(self, /) -> list[str]: ...

@final
class FinishReason:
    """
    Why an animation ended.

    `kind` is a string-compatible `FinishReasonKind` member.
    For `"stopped"`, `stop_mode` carries the requested [`StopMode`].
    For `"error"`, `message` carries a human-readable description.
    """
    def __repr__(self, /) -> str: ...
    @property
    def kind(self, /) -> FinishReasonKind: ...
    @property
    def message(self, /) -> str |None: ...
    @property
    def stop_mode(self, /) -> StopMode |None: ...

@final
class FolderFlagOp:
    """
    Folder-flag mutation mode used in
    [`AnimationOptions.before_flags`] / `after_flags`.

    Construct via [`FolderFlagOp.set`] (OR-set) or
    [`FolderFlagOp.exactly`] (mask-set).
    """
    def __repr__(self, /) -> str: ...
    @classmethod
    def exactly(cls, /, flags: int) -> FolderFlagOp:
        """
        Exactly-set semantics — matches the legacy
        `exactly_set_desktop_flags`.
        """
    @property
    def flags(self, /) -> int:
        """
        Flag word.
        """
    @property
    def kind(self, /) -> FolderFlagOpKind:
        """
        Operation kind, also accepted in dict and tuple flag operations.
        """
    @classmethod
    def set(cls, /, flags: int) -> FolderFlagOp:
        """
        OR-set semantics — matches the legacy `set_desktop_flags`.
        """

@final
class IconAnimationSpec:
    """
    Per-icon animation description.

    May be constructed programmatically or, when passed to
    [`DesktopController.animate`], as a plain dict with keys `id`,
    `target`, `duration`, `curve_x` / `curve_y` (or `curve` for both axes).
    """
    def __new__(cls, /, id: "str", target: "typing.Sequence[int]", duration: Duration, curve: Curve, curve_y: Curve |None = None, *, effect: Effect |None = None) -> IconAnimationSpec:
        """
        Build a spec with a single curve applied to both axes.
        """
    def __repr__(self, /) -> str: ...
    @property
    def id(self, /) -> str: ...
    @property
    def target(self, /) -> tuple[int, int]: ...

@final
class IconAnimationState:
    """
    Per-icon animation state captured by [`AnimationHandle.snapshot`].
    """
    def __repr__(self, /) -> str: ...
    @property
    def current(self, /) -> tuple[int, int]: ...
    @property
    def id(self, /) -> str: ...
    @property
    def is_final(self, /) -> bool:
        """
        `True` after the engine's final commit for this icon.
        """
    @property
    def origin(self, /) -> tuple[int, int]: ...
    @property
    def t(self, /) -> float:
        """
        Normalized time in `[0, 1]` for this icon.
        """
    @property
    def target(self, /) -> tuple[int, int]: ...

@final
class IconGrid:
    def __repr__(self, /) -> str: ...
    @property
    def capacity(self, /) -> int: ...
    @property
    def cell_size(self, /) -> tuple[int, int]: ...
    @property
    def columns(self, /) -> int: ...
    @property
    def icon_size(self, /) -> tuple[int, int]: ...
    @property
    def monitor_id(self, /) -> str: ...
    @property
    def origin(self, /) -> tuple[int, int] |None: ...
    @property
    def origin_inferred(self, /) -> bool: ...
    @property
    def rows(self, /) -> int: ...
    def to_dict(self, /) -> "dict[str, object]": ...
    @property
    def work_area(self, /) -> Rect: ...

@final
class IconSnapshot:
    """
    Read-only snapshot of a single desktop icon.
    """
    def __repr__(self, /) -> str: ...
    @property
    def display_name(self, /) -> str:
        """
        Human-readable name as shown on the desktop.
        """
    @property
    def id(self, /) -> str:
        """
        Opaque stable identifier for this icon (safe to JSON-round-trip).
        """
    @property
    def is_virtual(self, /) -> bool:
        """
        `True` for virtual items that have no filesystem path.
        """
    @property
    def path(self, /) -> str |None:
        """
        Absolute filesystem path, or `None` for virtual items
        (This PC, Recycle Bin, ...).
        """
    @property
    def position(self, /) -> tuple[int, int]:
        """
        Current position as a `(x, y)` tuple.
        """

@final
class MonitorInfo:
    """
    A single connected display in the virtual-screen coordinate system.

    See [`DesktopController.list_monitors`]. Bounds share the same
    coordinate space as icon positions.
    """
    def __repr__(self, /) -> str: ...
    @property
    def bounds(self, /) -> Rect:
        """
        Full monitor bounds in virtual-screen coordinates.
        """
    def contains(self, /, point: "typing.Sequence[int]") -> bool:
        """
        `True` if the given `(x, y)` point lies inside this monitor's
        full bounds.
        """
    @property
    def dpi(self, /) -> float: ...
    @property
    def id(self, /) -> str:
        """
        Stable-for-session identifier for the Windows display device.
        """
    @property
    def is_primary(self, /) -> bool:
        """
        `True` for the monitor that owns virtual coordinate `(0, 0)`.
        """
    @property
    def name(self, /) -> str:
        """
        Human-readable label.
        """
    @property
    def resolution(self, /) -> tuple[int, int]: ...
    @property
    def scale_factor(self, /) -> float:
        """
        Effective DPI scale factor (`1.0` = 96 DPI).
        """
    def to_dict(self, /) -> "dict[str, object]": ...
    @property
    def work_area(self, /) -> Rect:
        """
        Bounds excluding the taskbar and other reserved-space widgets.
        """

@final
class MotionContext:
    """
    Read-only view of the motion metadata handed to a
    [`Curve.from_motion_function`] sampler.
    """
    def __repr__(self, /) -> str: ...
    @property
    def distance_px(self, /) -> float: ...
    @property
    def duration_seconds(self, /) -> float: ...
    @property
    def origin(self, /) -> tuple[int, int]: ...
    def param(self, /, key: str, default: float |None = None) -> float |None:
        """
        Return `params[key]` or the provided default.
        """
    @property
    def params(self, /) -> dict[str, float]: ...
    @property
    def target(self, /) -> tuple[int, int]: ...

@final
class PlaybackHandle:
    def wait(self, /) -> PlaybackOutcome: ...
    def wait_timeout(self, /, timeout_seconds: float) -> PlaybackOutcome |None: ...

@final
class PlaybackOutcome:
    Closed: Final[PlaybackOutcome]
    Interrupted: Final[PlaybackOutcome]
    Reached: Final[PlaybackOutcome]
    def __eq__(self, value: object, /) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class PreparedAnimation:
    def __enter__(self, /) -> PreparedAnimation: ...
    def __exit__(self, /, _ty: "object", _value: "object", _traceback: "object") -> None: ...
    def cancel(self, /) -> None:
        """
        Release an unused session; idempotent. Does not move desktop icons.
        """
    def open_timeline(self, /) -> TimelineSession: ...
    def start(self, /) -> AnimationHandle:
        """
        Consume the prepared session. No compilation or artwork upload occurs here.
        """

@final
class ProceduralSource:
    def __new__(cls, /, passes: Sequence[RenderPass], *, parameters: Sequence[EffectParameter] |None = None, targets: Sequence[RenderTarget] |None = None, body_artwork: bool = False, label_artwork: bool = False) -> ProceduralSource: ...
    @property
    def body_artwork(self, /) -> bool: ...
    @property
    def label_artwork(self, /) -> bool: ...
    @property
    def parameters(self, /) -> list[EffectParameter]: ...
    @property
    def passes(self, /) -> list[RenderPass]: ...
    @property
    def targets(self, /) -> list[RenderTarget]: ...

@final
class Rect:
    """
    Axis-aligned pixel rectangle in virtual-screen coordinates.

    Uses inclusive-left / exclusive-right / inclusive-top / exclusive-
    bottom (matches Windows `RECT`).
    """
    def __repr__(self, /) -> str: ...
    def as_tuple(self, /) -> tuple[int, int, int, int]:
        """
        `(left, top, right, bottom)` — matches Windows `RECT` layout.
        """
    @property
    def bottom(self, /) -> int: ...
    def contains(self, /, point: "typing.Sequence[int]") -> bool:
        """
        `True` if the given `(x, y)` point lies inside this rectangle
        (inclusive of `left`/`top`, exclusive of `right`/`bottom`).
        """
    @property
    def height(self, /) -> int: ...
    @property
    def left(self, /) -> int: ...
    @property
    def right(self, /) -> int: ...
    @property
    def top(self, /) -> int: ...
    @property
    def width(self, /) -> int: ...

@final
class RenderPass:
    def __new__(cls, /, *, vertex: str |None = None, pixel: str |None = None, vertices: int = 6, count_parameter: str |None = None, multiplier: int = 0, topology: str = "triangles", inputs: Sequence[int] |None = None, output: int |None = None, blend: str = "over") -> RenderPass: ...
    @property
    def blend(self, /) -> str: ...
    @property
    def count_parameter(self, /) -> str |None: ...
    @property
    def inputs(self, /) -> list[int]: ...
    @property
    def multiplier(self, /) -> int: ...
    @property
    def output(self, /) -> int |None: ...
    @property
    def pixel(self, /) -> str |None: ...
    @property
    def topology(self, /) -> str: ...
    @property
    def vertex(self, /) -> str |None: ...
    @property
    def vertices(self, /) -> int: ...

@final
class RenderSession:
    """
    Prepared off-screen scene. No window, Shell position writes or visibility changes.
    Use as a context manager; render_at samples exact seconds, independent of wall time.
    """
    def __enter__(self, /) -> RenderSession: ...
    def __exit__(self, /, _ty: "object", _value: "object", _traceback: "object") -> None: ...
    def close(self, /) -> None: ...
    @property
    def duration(self, /) -> float: ...
    def render_at(self, /, seconds: float) -> CapturedFrame: ...

@final
class RenderTarget:
    def __new__(cls, /, width: int, height: int) -> RenderTarget: ...
    @property
    def height(self, /) -> int: ...
    @property
    def width(self, /) -> int: ...

@final
class Shader:
    @property
    def bytecode_size(self, /) -> int: ...
    @classmethod
    def compile(cls, /, source: "str | ShaderSource") -> Shader: ...

@final
class ShaderSource:
    def __new__(cls, /, pixel: str |None = None, *, vertex: str |None = None, pipeline: "ShaderPipeline | str" = "sprite", execution: ProceduralSource |None = None) -> ShaderSource: ...
    @classmethod
    def builtin(cls, /, name: "BuiltinShader | str") -> ShaderSource: ...
    @property
    def execution(self, /) -> ProceduralSource |None: ...
    @property
    def pipeline(self, /) -> ShaderPipeline: ...
    @property
    def pixel(self, /) -> str |None: ...
    @property
    def vertex(self, /) -> str |None: ...

@final
class StartContext:
    """
    Argument passed to `on_start` callbacks.
    """
    def __repr__(self, /) -> str: ...
    @property
    def missing_icons(self, /) -> int: ...
    @property
    def total_icons(self, /) -> int: ...

@final
class StopMode:
    """
    How an animation should leave the desktop when
    [`AnimationHandle.stop`] is invoked.
    """
    LeaveInPlace: Final[StopMode]
    TeleportToTarget: Final[StopMode]
    def __eq__(self, value: object, /) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class TickContext:
    """
    Argument passed to `on_tick` callbacks.
    """
    def __repr__(self, /) -> str: ...
    @property
    def active_icons(self, /) -> int:
        """
        Number of icons still moving.
        """
    @property
    def elapsed_seconds(self, /) -> float:
        """
        Wall-clock seconds since the animation started.
        """
    @property
    def finalized_icons(self, /) -> int:
        """
        Number of icons that have reached their target.
        """
    @property
    def progress(self, /) -> float:
        """
        Global progress in `[0, 1]`.
        """

@final
class TimelineCloseMode:
    LeaveInPlace: Final[TimelineCloseMode]
    RestoreOrigins: Final[TimelineCloseMode]
    TeleportToTarget: Final[TimelineCloseMode]
    def __eq__(self, value: object, /) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...

@final
class TimelineSession:
    """
    Persistent, seekable playback opened by ``PreparedAnimation.open_timeline``.

    Reaching an endpoint pauses without closing the overlay. Use as a context
    manager to restore original icon positions on exit, including exceptions.
    """
    def __enter__(self, /) -> TimelineSession: ...
    def __exit__(self, /, _ty: "object", _value: "object", _traceback: "object") -> None: ...
    def capture(self, /) -> CapturedFrame:
        """
        Capture the last submitted overlay frame, without changing playback.
        """
    def close(self, /, mode: TimelineCloseMode |None = None) -> FinishReason:
        """
        Close the overlay, restoring original positions unless another mode is given.
        """
    def final_commit(self, /) -> FinalCommitOutcome |None: ...
    def finish_reason(self, /) -> FinishReason |None: ...
    def missing_icons(self, /) -> list[str]: ...
    def pause(self, /) -> None: ...
    def play_to(self, /, position: float, speed: float = 1.0) -> PlaybackHandle:
        """
        Play toward a normalized position in [0, 1] at a positive finite speed.
        """
    def position(self, /) -> float: ...
    def real_icons_visible(self, /) -> bool: ...
    def seek(self, /, position: float) -> None:
        """
        Pause and show the requested normalized position in [0, 1].
        """
    def seek_and_capture(self, /, position: float) -> CapturedFrame:
        """
        Pause, seek and capture as one worker operation. Position is normalized.
        """
    def set_real_icons_visible(self, /, visible: bool) -> None: ...
    def set_speed(self, /, speed: float) -> None: ...
    def snapshot(self, /) -> list[IconAnimationState]: ...
    def speed(self, /) -> float: ...
    def state(self, /) -> TimelineState: ...

@final
class TimelineState:
    Closed: Final[TimelineState]
    Paused: Final[TimelineState]
    Playing: Final[TimelineState]
    def __eq__(self, value: object, /) -> bool: ...
    def __int__(self, /) -> int: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...

def init_logging(level: str |None = None, target: "LogTarget | str" = "loguru") -> bool:
    """
    Route this library's diagnostics somewhere useful.

    Called automatically at import time with the defaults, so configuring
    a loguru sink is usually all you need. Call this explicitly to change
    the level or switch sinks.
    """

class RustyDesktopError(Exception):
    'Base class for all errors raised by rusty-desktop-icons.'
    ...

class AnimationBusy(RustyDesktopError):
    'Raised when a caller asks for exclusive animation access but another animation is already running.'
    ...

class BackendUnavailable(RustyDesktopError):
    'Raised when the desktop backend could not be initialised or acquired.'
    ...

class ComError(RustyDesktopError):
    'Raised when a COM / Win32 call returned a failure HRESULT.'
    ...

class IconNotFound(RustyDesktopError):
    'Raised when a requested icon id is not present on the desktop.'
    ...

class InvalidCurve(RustyDesktopError):
    'Raised when a curve fails validation or a sampled Python callable returned an unusable value.'
    ...

class InvalidDuration(RustyDesktopError):
    'Raised when a Duration policy cannot be resolved.'
    ...

class InvalidEffect(RustyDesktopError):
    'Invalid shader source or effect configuration.'
    ...

class InvalidGrid(RustyDesktopError):
    'Unavailable grid geometry or no collision-free destination.'
    ...

class UnsupportedPlatform(RustyDesktopError):
    'Raised when no compiled backend supports the current OS.'
    ...

class WorkerCrashed(RustyDesktopError):
    'Raised when the animation worker thread has stopped unexpectedly.'
    ...

if sys.platform == 'win32':
    def _folder_flag_catalog() -> list[tuple[int, str, str, str]]:
        ...
    def _builtin_shader_catalog() -> list[tuple[str, str]]:
        ...
