"""Generate public typing from PyO3 metadata; never infer callable signatures."""

from __future__ import annotations

import argparse
import ast
import difflib
import importlib.machinery
import importlib.util
from pathlib import Path
import subprocess
import sys
import tempfile
from textwrap import indent
from types import ModuleType

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "crates/rdi-python/python/rusty_desktop_icons"
HEADER = "# Generated by scripts/generate-stubs.py. Do not edit.\n"


def load_native(build: Path) -> ModuleType:
    binaries = [path for path in (build / "maturin").iterdir()
                if "_rusty_desktop_icons" in path.name
                and path.suffix in {".dll", ".so", ".dylib", ".pyd"}]
    if len(binaries) != 1:
        raise RuntimeError(f"Expected one Maturin native artifact, found {binaries}")
    binary = binaries[0]
    name = "_rusty_desktop_icons"
    loader = importlib.machinery.ExtensionFileLoader(name, str(binary))
    spec = importlib.util.spec_from_file_location(name, binary, loader=loader)
    if spec is None:
        raise RuntimeError(f"Cannot load freshly built extension: {binary}")
    module = importlib.util.module_from_spec(spec)
    loader.exec_module(module)
    return module


def complete_native(source: str, native: ModuleType) -> str:
    tree = ast.parse(source)
    declared = {
        node.name for node in tree.body
        if isinstance(node, (ast.ClassDef, ast.FunctionDef))
    } | {
        node.target.id for node in tree.body
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name)
    }
    missing = {
        name: getattr(native, name) for name in dir(native)
        if not name.startswith("_") and name not in declared
    }
    for name, value in missing.items():
        if not isinstance(value, type) or not issubclass(value, Exception):
            raise RuntimeError(f"PyO3 did not generate public export {name!r}")
    lines = source.splitlines()
    windows_declarations: list[str] = []
    for node in reversed(tree.body):
        if isinstance(node, ast.FunctionDef) and node.name in {"_folder_flag_catalog", "_builtin_shader_catalog"}:
            windows_declarations.append(ast.unparse(node))
            del lines[node.lineno - 1:node.end_lineno]
            continue
        if (isinstance(node, ast.FunctionDef) and node.name == "__getattr__") or (
            isinstance(node, ast.ImportFrom) and node.module == "_typeshed"
        ):
            del lines[node.lineno - 1:node.end_lineno]
    text = "\n".join(line.rstrip() for line in lines).strip() + "\n"
    pending = dict(missing)
    while pending:
        ready = [name for name, value in pending.items()
                 if value.__base__.__name__ not in pending]
        if not ready:
            raise RuntimeError("Cannot order exception inheritance")
        for name in sorted(ready):
            value = pending.pop(name)
            base = value.__base__.__name__
            if base not in declared and base != "Exception":
                raise RuntimeError(f"Undocumented exception base: {base}")
            text += f"\nclass {name}({base}):\n    {value.__doc__!r}\n    ...\n"
            declared.add(name)
    if sys.platform != "win32":
        checked = ast.parse((PACKAGE / "_rusty_desktop_icons.pyi").read_text(encoding="utf-8"))
        for node in checked.body:
            if isinstance(node, ast.If) and ast.unparse(node.test) == "sys.platform == 'win32'":
                windows_declarations.extend(ast.unparse(member) for member in node.body)
    if windows_declarations:
        text += "\nif sys.platform == 'win32':\n" + indent("\n".join(windows_declarations), "    ") + "\n"
    return (HEADER + "from __future__ import annotations\nimport sys\nimport typing\n"
            "from ._builtin_shaders import BuiltinShader\n"
            "from ._enums import KeyframeInterp, LogTarget\n\n" + text)


def wrapper_stub(native: ModuleType) -> str:
    tree = ast.parse((PACKAGE / "__init__.py").read_text(encoding="utf-8"))
    result = [HEADER.rstrip()]
    for node in tree.body:
        if isinstance(node, ast.If) and ast.unparse(node.test) == "sys.platform == 'win32'":
            for statement in node.body:
                if isinstance(statement, ast.ImportFrom) and statement.module == "_flags":
                    result.extend([
                        "import sys",
                        "if sys.platform == 'win32':",
                        "    from ._flags import FolderFlag as FolderFlag",
                    ])
            continue
        if not isinstance(node, ast.ImportFrom):
            continue
        if node.module == "_rusty_desktop_icons":
            for alias in node.names:
                if not hasattr(native, alias.name):
                    raise RuntimeError(f"Wrapper exports missing native name {alias.name}")
                result.append(
                    f"from ._rusty_desktop_icons import {alias.name} as {alias.asname or alias.name}"
                )
        elif node.module in {"_enums", "_builtin_shaders"}:
            for alias in node.names:
                result.append(f"from .{node.module} import {alias.name} as {alias.asname or alias.name}")
        elif node.module == "_logging":
            for alias in node.names:
                if alias.name != "LOGGER_NAME":
                    raise RuntimeError(f"Unhandled Python wrapper export {alias.name}")
                result.append(f"{alias.asname or alias.name}: str")
        else:
            raise RuntimeError(f"Unhandled wrapper import {node.module}")
    return "\n".join(result) + "\n"


def flag_stub(native: ModuleType) -> str:
    tree = ast.parse((PACKAGE / "_flags.py").read_text(encoding="utf-8"))
    definition = next(node for node in tree.body
                      if isinstance(node, ast.ClassDef) and node.name == "_FolderFlag")
    definition.name = "FolderFlag"
    members = [ast.Assign(targets=[ast.Name(id=name, ctx=ast.Store())], value=ast.Constant(bits))
               for bits, name, _, _ in native._folder_flag_catalog()]
    for node in definition.body:
        if isinstance(node, ast.FunctionDef):
            docstring = ast.get_docstring(node)
            node.body = ([ast.Expr(value=ast.Constant(docstring))] if docstring else [])
            node.body.append(ast.Expr(value=ast.Constant(Ellipsis)))
    definition.body[1:1] = members
    ast.fix_missing_locations(definition)
    return (HEADER + "from __future__ import annotations\nfrom enum import IntFlag\n\n"
            + ast.unparse(definition) + "\n")


def builtin_shader_source(native: ModuleType) -> str:
    members = "\n".join(f"    {name} = {value!r}" for name, value in native._builtin_shader_catalog())
    return (HEADER + '"""Built-in names generated from the Windows Rust shader catalog."""\n\n'
            "from ._enums import _StringEnum\n\n\nclass BuiltinShader(_StringEnum):\n"
            '    """Built-in shader sources; compilation requires Windows."""\n\n'
            + members + "\n")


def enum_stub(source: str) -> str:
    tree = ast.parse(source)
    tree.body = [node for node in tree.body
                 if not (isinstance(node, ast.ClassDef) and node.name == "_StringEnum")
                 and not (isinstance(node, ast.ImportFrom) and node.module == "_enums")]
    if not any(isinstance(node, ast.ImportFrom) and node.module == "enum"
               for node in tree.body):
        tree.body.insert(0, ast.ImportFrom(module="enum", names=[ast.alias(name="Enum")], level=0))
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and any(
            isinstance(base, ast.Name) and base.id == "_StringEnum" for base in node.bases
        ):
            node.bases = [ast.Name(id="str", ctx=ast.Load()), ast.Name(id="Enum", ctx=ast.Load())]
        if isinstance(node, ast.FunctionDef):
            node.body = [ast.Expr(value=ast.Constant(Ellipsis))]
    ast.fix_missing_locations(tree)
    return HEADER + ast.unparse(tree) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail on drift without writing files")
    args = parser.parse_args()
    build = ROOT / "target/stubgen"
    with tempfile.TemporaryDirectory() as temporary:
        subprocess.run([
            sys.executable, "-m", "maturin", "generate-stubs",
            "-m", str(ROOT / "crates/rdi-python/Cargo.toml"),
            "--target-dir", str(build), "--out", temporary,
            "-i", sys.executable,
        ], check=True, cwd=ROOT)
        native = load_native(build)
        raw = Path(temporary) / "rusty_desktop_icons/_rusty_desktop_icons.pyi"
        outputs = {
            "_rusty_desktop_icons.pyi": complete_native(raw.read_text(encoding="utf-8"), native),
            "__init__.pyi": wrapper_stub(native),
        }
        if sys.platform == "win32":
            outputs["_flags.pyi"] = flag_stub(native)
            outputs["_builtin_shaders.py"] = builtin_shader_source(native)
        builtin_source = outputs.get("_builtin_shaders.py")
        if builtin_source is None:
            builtin_source = (PACKAGE / "_builtin_shaders.py").read_text(encoding="utf-8")
        outputs["_builtin_shaders.pyi"] = enum_stub(builtin_source)
        outputs["_enums.pyi"] = enum_stub((PACKAGE / "_enums.py").read_text(encoding="utf-8"))
        stale = False
        for filename, content in outputs.items():
            ast.parse(content, filename=filename)
            path = PACKAGE / filename
            if args.check:
                old = path.read_text(encoding="utf-8") if path.exists() else ""
                if old != content:
                    stale = True
                    sys.stdout.writelines(difflib.unified_diff(
                        old.splitlines(keepends=True), content.splitlines(keepends=True),
                        fromfile=str(path), tofile="regenerated/" + filename,
                    ))
            else:
                path.write_text(content, encoding="utf-8", newline="\n")
        if stale:
            raise SystemExit("Stubs are stale. Run python scripts/generate-stubs.py")
        print("Generated stubs match the PyO3 API." if args.check else "Generated package stubs.")


if __name__ == "__main__":
    main()